name: CI

on:
  push:
    branches:
      - main

jobs:
  e2e:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install Yarn Dependencies
        run: yarn install

      - name: Install Pod Dependencies
        run: npx pod-install

      - name: install npm libs and pods
        run: |
          yarn install
          npx pod-install

      - name: Install Detox Dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Run Detox Build
        run: yarn e2e:ios:build

      - name: Run Detox Test(s)
        run: yarn e2e:ios:run
